services:
  lunch-coupon:
    build: .
    depends_on:
      - postgres
    env_file:
      - .dockerenv
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://localhost:5432
    networks:
      - default
    ports:
      - 5000:5000

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - default
    ports:
      - 5432:5432
