"""empty message

Revision ID: 20853f1a6990
Revises: 96ee226dbec1
Create Date: 2023-07-12 15:09:11.959481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20853f1a6990'
down_revision = '96ee226dbec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_address', sa.String(length=150), nullable=True))
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_email_address'), ['email_address'], unique=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_index(batch_op.f('ix_user_email_address'))
        batch_op.create_index('ix_user_email', ['email'], unique=False)
        batch_op.drop_column('email_address')

    # ### end Alembic commands ###
