"""empty message

Revision ID: 95bfe64bcf0a
Revises: a8fe4a9e0c40
Create Date: 2023-07-14 04:08:30.221767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95bfe64bcf0a'
down_revision = 'a8fe4a9e0c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch_card', schema=None) as batch_op:
        batch_op.drop_column('created_on')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lunch_card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_on', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
