on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/cache@v3
        id: cache-python-environment
        with:
          path: ${{ env.pythonLocation }}
          key: 'cache-python-environment'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    needs: ['build']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: actions/cache@v3
        id: cache-python-environment
        with:
          path: ${{ env.pythonLocation }}
          key: 'cache-python-environment'
      - name: Lint with ruff
        if: success() || failure()
        run: |
          # check what lint errors there are
          ruff check .
          # # stop the build if there are Python syntax errors or undefined names
          # ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # # default set of ruff rules with GitHub Annotations
          # ruff --format=github --target-version=py37 .