on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get cached dependencies
        uses: actions/setup-python@v4
        with:
          cache: 'pip'
      - name: Lint with ruff
        if: success() || failure()
        run: |
          # check what lint errors there are
          ruff check .
          # # stop the build if there are Python syntax errors or undefined names
          # ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
          # # default set of ruff rules with GitHub Annotations
          # ruff --format=github --target-version=py37 .